import { iLocalization } from '../iLocalization';

const en: iLocalization = {
  en: 'English',
  vi: 'Vietnamese',
  ja: 'Japanese',
  ko: 'Korean',
  de: 'German',
  th: 'Thailand',
  sk: 'Slovak',
  hi: 'Hindi',
  zh: 'Chinese',
  login: 'Login',
  logout: 'Logout',
  signup: 'Sign Up',
  home: 'Home',
  cart: 'Cart',
  addStream: 'Add Stream',
  notification: 'Notifications',
  aiStream: 'AI Stream',
  categories: 'Categories',
  profile: 'Profile',
  loading: 'Loading...',
  changeLanguage: 'Switch Language',
  tokenTimeout: 'Session Expired',
  welcomeBack: 'Welcome Back',
  welcomeBackSubTxt: 'Log in to Great Deals!',
  or: 'or',
  dontHaveAccount: `Don't have an account?`,
  forgotPassword: 'Forgot Password',
  rememberMe: 'Remember me',
  myUpload: 'My Uploads',
  createVideo: 'Create Video',
  delete: 'Delete',
  edit: 'Edit',
  deleteAiStream: 'Delete Video',
  subDeleteAiStream: 'Are you sure you want to delete this video?',
  keepIt: 'Keep',
  deleteIt: 'Delete',
  saveClip: 'Saved Clips',
  createStream: 'Create AI Stream',
  reportUs: 'Report video',
  report: 'Report',
  block: 'Block',
  whatIsIssue: 'What is the issue?',
  inappropriateContent: 'Inappropriate content',
  spamMisleading: 'Spam or misleading',
  copyrightInfringement: 'Copyright infringement',
  harassmentBullying: 'Harassment or bullying',
  other: 'Other',
  sendReport: 'Send report',
  goToLogin: 'Go to login',
  goToLoginSubTxt: 'Great Deals Await!',
  yes: 'Yes',
  no: 'No',
  signUpTxt: 'Create Account',
  subSignUpTxt: 'We have 3 steps for account creation',
  chooseDetail: 'Take A Health Assessment',
  chooseDetailSub: 'Your wellness journey begins with clarity!',
  shareDeal: 'Discover Your Risk Factors ',
  shareDealSub: 'Catch risks early, stay strong and happy!',
  optionFree: 'Explore Our Action Plan For You',
  optionFreeSub: 'Unlock your personalised wellness guides!',
  alreadyHaveAnAccount: 'Already have an account?',
  basicInterest: 'Interests',
  chooseLanguage: 'Choose Language',
  back: 'Back',
  next: 'Next',
  createAccount: 'Create Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  birthday: 'Birthday',
  phone: 'Phone',
  email: 'Email',
  password: 'Password',
  yourInterest: 'Your Interests',
  iAgree: 'I agree to',
  termsAndPrivacy: 'Terms & Privacy',
  conditions: 'conditions.',
  addEmail: 'Add emails to invite & earn',
  addLucky: '✨ 1 lucky wheel spins',
  weekly: 'weekly',
  skip: 'Skip',
  sendNow: 'Send Now',
  spin: 'Spin',
  luckyWheel: 'Lucky Wheel',
  rewards: 'Rewards',
  friendsInvited: 'Friends Invited',
  days: 'Days',
  remainingTime: 'Remaining Time',
  toExpiry: 'To Expiry',
  selectYourProduct: 'Select your Product',
  maximumSize: 'Maximum size 100 MB \nVideo duration 120 Seconds.',
  fileFormats: 'File formats',
  recommendedMp4: 'Recommended ".mp4". Other major formats are supported',
  aspectRatios: 'Aspect ratios',
  recommendedRecom: 'Recommended 16 9 for landscape, 9 16 for vertical.',
  selectVideoToUpload: 'Select video to upload',
  selectVideo: 'Select video',
  englishEUStore: 'English - EU Store',
  germanEUStore: 'German - EU Store',
  thailandStore: 'Thailand - Thailand Store',
  myProfile: 'My profile',
  inviteFriends: 'Invite friends',
  inviteFriendsSubTxt: 'Invite your friends and get 100 Credits for each invites.',
  blockList: 'Block list',
  ourSocials: 'Our socials',
  discoverBestDealsTitle: 'Discover the Best Deals',
  discoverBestDealsDescription: 'Shop top deals and exclusive offers just for you!',
  earnRewardsTitle: 'Earn Rewards as You Shop',
  earnRewardsDescription: 'Earn credits and bonuses shop more, save more!',
  shopWithConfidenceTitle: 'Shop with Confidence',
  shopWithConfidenceDescription: 'Shop more, earn rewards, and save big!',
  getTheBestAndBeHappy: 'Get the Best and\n Be Happy',
  best: 'Best',
  and: 'and',
  be: 'Be',
  happy: 'Happy',
  getStarted: 'Get started',
  affiliateCode: 'Affiliate code',
  personalInformation: 'Personal information',
  fullName: 'Full name',
  displayName: 'Display name',
  emailAddress: 'Email address',
  myInterest: 'My interest',
  addInterest: 'Add interest',
  editPersonalInformation: 'Edit personal information',
  close: 'Close',
  add: 'Add',
  update: 'Update',
  unBlock: 'Unblock',
  today: 'Today',
  yesterday: 'Yesterday',
  streamSharedSuccessfully: 'Stream shared successful',
  copySuccess: 'Copy successful',
  blockUserSuccess: 'Block user successful',
  follow: 'Follow',
  following: 'Following',
  loadingStreamError: 'AI Stream error, please try again',
  minPassword: 'Password must have at least 8 characters',
  createAccountSuccess: 'Account created',
  noThanks: 'No thanks',
  loginNow: 'Login now',
  followers: 'Followers',
  errorSystem: 'System error, please try again later',
  changeVideo: 'Change',
  discardPost: 'Discard post',
  videoTitle: 'Video title',
  selectProduct: 'Select product',
  shortDescription: 'Short Description',
  invalidEmail: 'Invalid email!',
  atLeastOneEmail: 'You need to enter at least one email',
  selectVideoFormLib: 'Open library',
  takeVideoLive: 'Open camera',
  requiredField: 'Required field',
  reportedSuccessfully: 'Thank you for your report.',
  editAiStream: 'Edit stream',
  deleteAiStreamSuccess: 'Delete video success',
  deleteAiStreamFailed: 'Delete video failed',
  businessName: 'Business name',
  updateProfileSuccess: 'Update profile success',
  updateProfileFailed: 'Update profile failed',
  gotoSetting: 'Go to setting',
  cancel: 'Cancel',
  askCameraTitle: 'Allow AISolomon to access your camera?',
  askCameraMessage: 'Allow to access your camera to take photos and videos',
  askLibraryTitle: 'Allow AISolomon to access your gallery?',
  askLibraryMessage: 'Allow to access your gallery to take photos and videos',
  avatarUpdated: 'Profile picture updated',
  somethingWrong: 'Something went wrong, please try again',
  somethingWrongWhenOpenLink: 'Something went wrong when open link, please try again',
  descriptionLuckyWheel: 'Spin the wheel for a chance to win great prizes.',
  gotIt: 'Got it',
  congratulation: 'Congratulations',
  congratulationTxt: 'You have won',
  turnRemain: 'Spins remaining',
  connectToServerErr: 'Network connection error, please try again',
  waitToConfirm: 'Pending confirmation',
  changeLanguageSuccess: 'Language has been switched successfully',
  changeLanguageFailed: 'Network connection error. Please try again later.',
  spinTurn: 'Spin turns',
  warning: 'Product Tag Error',
  pleaseBuyProduct: 'Past purchase required to enable Product Tags.',
  likedWillAppearHere: 'Liked videos will appear here',
  somethingWentWrong: 'Something went wrong',
  errConent: 'There is a problem with the network. Please try again in a few minutes.',
  descriptionLetter: 'Yes, I would like to subscribe to the free AISolomon newsletter. (You may unsubscribe at any time.)',
  copyLink: 'Copy link',
  shareWithFriend: 'Share with a friend',
  shareWithFriendSubText: 'Refer friends to earn Lucky Wheels, winning up to 200 credits!',
  topProduct: 'Top Products',
  saving: 'Savings',
  notiWillAppearHere: 'Notifications will appear here',
  videoGuide: 'Video Guide',
  iUnderstood: 'I understand',
  search: 'search',
  titleModalReportAndBlock: 'Report & Block',
  descriptionModalReportAndBlock: 'Submit reason & block user.',
  unsaveSuccess: 'Unsave successful',
  makeChanges: 'Edit',
  makeChangesSubText: 'You can edit or delete post',
  view: 'View',
  dontShowAgain: `Don't show this again`,
  love: 'Likes',
  addAnother: 'Add another',
  invalidPhone: 'Invalid phone number',
  threeStepCreateAccount: 'Create Account in 3 Steps',
  confirmPassword: 'Confirm password',
  basicInformation: 'Basic information',
  chooseGallery: 'Choose gallery',
  updateVideo: 'Update video',
  preview: 'Preview',
  addProduct: 'Add product',
  addACatchyTitle: 'Add Title',
  addAShortDes: 'Add Short Description',
  rePassword: 'Passwords do not match. Please enter again.',
  daysRemaining: 'Days remaining',
  deleteOrDeactivate: 'Delete or deactivate',
  deactivateAccount: 'Deactivate account',
  deleteAccount: 'Delete Account',
  deleteOrDeactivateAccount: 'Delete or deactivate account',
  deleteAccountPermanently: 'Delete account permanently',
  titleDeleteOrDeactivate: `If you want to leave AISolomon temporarily, simply deactivate your account. If you choose to delete your account instead, you won't be able to recover it after 30 days.`,
  contentDeleteOrDeactivate: 'No one can see your account, including all content that is stored in it. Reactivate your account and recover all content anytime.',
  contentTwoDeleteOrDeactivate: 'Your account and content will be deleted permanently. You may cancel the deletion request by reactivating your account within 30 days.',
  ifYouDeactivateYourAccount: 'If you deactivate your account',
  ifYouDeleteYourAccount: 'If you delete your account',
  noOneSeesAccount: 'No one will see your account and content.',
  infoNotStoredVisible: 'Information that isn\'t stored in your account, such as direct messages, may still be visible to others.',
  shopWithMeKeepsData: 'AISolomon will continue to keep your data so that you can recover it when you reactivate your account.',
  reactivateAnytime: 'You can reactivate your account and recover all content anytime by using the same login details.',
  shopWithMeNoAccess: 'You won\'t be able to log in and use any AISolomon services with that account.',
  loseVideos: 'You will lose access to all your videos.',
  draftsRemoved: 'Information that is not stored in AISolomon servers, such as drafts, will be removed and you won\'t be able to download it.',
  noRefunds: 'You won\'t be able to get a refund on any items you purchased or received.',
  deactivate: 'Deactivate',
  noThank: 'No thanks',
  deactivateNow: 'Deactivate Now',
  activeAnyTime: 'You can activate your account anytime',
  affterADay: 'After 30 days, your account and data will be deleted permanently.',
  deleteNow: 'Delete now',
  continue: 'Continue',
  accountDeactivatedSuccess: 'Account deactivation successful.',
  accountDeactivatedMessage: 'Your account is deactivated successfully. If you want to use the app, please activate your account.',
  goToShop: 'Shop Now',
  activeMyAccount: 'Activate Account',
  welcomeBackText1: 'Your account is deactivated and will be deleted in ',
  welcomeBackTextTime: '20 days',
  welcomeBackText2: '. If you want to use the app, please activate your account',
  registerAccountSuccess: 'Register success',
  createInterestSuccees: 'Create interest success',
  uploadVideos: 'Upload Videos & earn up to 3 spins daily (max 200 credits).',
  viewVideos: 'View 20 videos, share 3, and get 1 Lucky Wheel daily.',
  sendInvites: 'Send 10 invites and win 2 Lucky Wheels per week.',
  earnLuckyWheel: 'Earn 1 Lucky Wheel per friend who signs up using your referral link.',
  watchButton: 'Watch',
  iAgreed: 'I agree',
  endUserLicenseAgreement: 'end user license agreement',
  upload: 'Upload',
  share: 'Share',
  invite: 'Invite',
  dontShareDob: `I don't want to share my date of birth`,
  enough18: 'I am at least 18 years old',
  outOfTurns: 'You have run out of spins',
  noResultsFound: 'No results found',
  noVideoFound: 'No videos found',
  posts: 'Posts',
  actions: 'Actions',
  removedVideo: 'Remove video',
  descriptionRemovedVideo: 'Are you sure you want to delete this video?',
  permanentlyDeleteVideo: 'Permanently delete video',
  manageUser: 'Manage User',
  welcome: 'Welcome',
  descriptionWelcom: 'Login now to post videos, spin the Lucky Wheel and win exciting prizes!',
  previousResults: 'Previous results',
  youGot: 'You got',
  updateInviteCodeSuccess: 'Update Invite Code Success',
  product: 'Product',
  products: 'Products',
  moreInfo: 'More info',
  productDetails: 'Products details',
  shopNow: 'Shop now',
  save: 'Save',
  uHaveNotification: 'You have {{number}} new notifications!',
  uHaveNoNotification: 'You have no notifications.',
  promotion: 'Promotion',
  description: 'Description',
  benefits: 'Benefits',
  ingredients: 'Ingredients',
  showNotProduct: `No products available in your area. Please update your shipping address to see what's in stock near you.`,
  whatIsInviteCodeModalTitle: 'Referral Code Required',
  whatIsInviteCode: 'How to get a Referral Code?',
  whatIsInviteCodeSubTxt: 'If someone has introduced you to AISolomon, please contact that person for a Referral Code.',
  emptyTextAwardHistory: 'Reward will appear here!',
  submit: 'Submit',
  deleteVideo: 'Delete video',
  emptyListProduct: 'Past purchases required to create new videos.',
  credits: 'Credits',
  goShop4Free: 'Go Shop4Free',
  noSaveProductYet: 'Has no save video list yet',
  deals: 'Deals',
  goShop4FreeDes: 'Earn credits to redeem products\nfor up to 100% free!',
  passwordRecovery: 'Password recovery',
  passwordRecoverySubTxt: 'We will send you a confirmation email. Click the link in that email in order to change your password.',
  sendEmail: 'Send email',
  passwordResetSubTxt: 'If the provided email address is registered, a confirmation email including a password reset link has been sent.',
  passwordResetBtn: 'Go to Login',
  noUserFound: 'No user found!',
  noNotification: 'No new notifications found!',
  waitForGenLinkShare: 'Please wait for get link for share',
  recoveryPasswordSuccess: 'Password recovery request successful please check your email',
  titleUpdateVersionApp: 'New Update Released!',
  subUpdateVersionApp: 'Update your app to gain access to the latest features!',
  btnUpdateVersionApp: 'Get Latest Version',
  titleMaintenance: 'Ongoing Maintenance',
  subMaintenance: 'We are upgrading the platform to bring you a better experience.',
  timeRemaining: 'Estimated completion',
  iAgreeToTermsPrivacyAndEula: 'Terms, Privacy and EULA',
  cantRemoveAllInterest: `you can't remove all interest`,
  noSpinsLeft: 'No spins left',
  earnMoreLuckyWheels: 'Earn more Lucky Wheels',
  gotoEarn: 'Go to Earn',
  hide: 'Hide',
  more: 'See more',
  connectVideoServerErr: 'Connect to Video Server got error',
  seeRecommendForYou: 'See recommendations for you',
  aiStory: 'AI story',
  addImage: 'Add image',
  addVideo: 'Add video',
  before: 'Before',
  after: 'After',
  describeYourImage: 'Describe your image',
  describeYourVideo: 'Describe your video',
  generateStoryModeVideo: 'Generate story mode video',
  aiVideo: 'Ai video',
  publishVideo: 'Publish video',
  reGenerateVideo: 'Re-Generate video',
  selectImage: 'Select image',
  describeYourProduct: 'Describe your product',
  deleteDraf: 'Delete draft',
  generatingYourStory: 'Generating your story',
  pleaseKeepAppOpen: 'Please keep the app open',
  intro: 'Intro',
  selectVideoOrImage: 'Select\nVideo/Image',
  require: 'Required',
  postVideo: 'Post video',
  storyMode: 'Story mode',
  createStorySuccess: `We’re processing your AI Story.\nYou’ll be notified once it’s ready`,
  fileSizeCantOver: 'File size cant over {{maxSize}}MB',
  writeIntroductionText: 'Write introduction text',
  writeBeforeText: 'Write before text',
  writeAfterText: 'Write after text',
  writeProductText: 'Write product text',
  notYourNotification: 'This notification does not belong to the current account',
  takePhotoOrVideo: 'Take Photo or Video',
  askMicroTitle: 'Allow AISolomon to access your microphone?',
  askMicroMessage: 'Allow access to your microphone to record audio?',
  retake: 'Retake',
  useThis: 'Use this',
  fileNotSupport: 'File not supported',
  searchPlaceHolder: 'Search video, products...',
  notFoundVideo: 'Error! Video not found',
  updateInterestSuccess: 'Update interest success',
  videoRanking: 'Video ranking',
  yourVideoOverview: 'Your Video Overview',
  yourPerformance: 'Your performance',
  totalLikes: 'Total likes',
  allTimeVideoStars: 'All time video stars',
  lastWeekVideoStars: 'Last week video stars',
  todayVideoStars: `Today's video stars`,
  allTimeTopVideo: 'All time top video',
  lastWeekTopVideo: 'Last week top video',
  todaysTopVideo: `Today's top video`,
  videoStarsRanking: 'Video Stars Ranking',
  noRankingYet: 'No ranking yet!',
  uploadClaimTheTopSpot: 'Upload your videos now and be the first to claim the top spot!',
  rank: 'Rank',
  user: 'User',
  likes: 'Likes',
  watch: 'Watch',
  videos: 'Videos',
  avgLikePerVideo: 'Avg {{number}} likes per video',
  youNeedUpload: 'You need to Upload {{number}} videos to reach 1st rank.',
  uploadVideosToWin: 'Upload videos to win!!!',
  shareTopVideo: 'Share top video',
  postNewVideo: 'Post new video',
  toViewYourPerformance: 'to view your performance',
  rankingPeriod: 'Ranking Period: {{startTime}} to {{endTime}}',
  totalVideos: 'Total videos',
  avgLikes: 'Avg likes',
  topUserRank: 'Top user rank',
  topCreatorsRealImpact: `Top Creators, Real Impact.See Who’s Leading the Stream!`,
  winAmazingPrizes: 'Win amazing prizes!',
  videoStarHeading: 'Are you the AISolomon VIDEO Star?',
  videoStarSubheading: 'Win iPhones & laptops & trips and over 1 million credits in valuable prizes!',
  prize1stPlace: '1 Luxury all-inclusive trip to the Maldives for 2 people!!!',
  prize2ndPlace: '1 Luxury Apple MacBook Air laptop',
  prize3rdTo5thPlace: '1 iPhone 16 each',
  creditsEach: 'Credits each',
  youAreLeading: `You're leading! Don't forget to upload to stay on top!`,
  newUserProgram: 'New User Program',
  videoStarRanking: 'Video star ranking',
  noVideoAvailable: 'No videos available',
  setting: 'Settings',
  biometricAuthPrompt: 'Authenticate to login with biometrics',
  usePassword: 'Use Password',
  openBiometricId: 'Use biometrics to log in',
  // Biometric error messages
  error: 'Error',
  noSavedCredentials: 'No saved login credentials found for biometric authentication',
  failedDecryptCredentials: 'Failed to decrypt saved credentials',
  biometricTempUnavailable: 'Biometric Temporarily Unavailable',
  tooManyFailedAttempts: 'Too many failed attempts. Please use your password to log in.',
  biometricLocked: 'Biometric Locked',
  biometricTempLocked: 'Your biometric authentication is temporarily locked. Please use your password instead.',
  authenticationFailed: 'Authentication Failed',
  authenticationError: 'An error occurred during authentication',
  biometricAuthentication: 'Biometric Authentication',
  biometricNoAccessMessage: 'Biometric authentication has no access, please enable it in settings.',
  unknownError: 'Unknown error',
  success: 'Success',
  biometricAuthSuccess: 'Biometric authentication successful',
  biometricPermissionGranted: 'Biometric permission granted',
  shop4Free: 'SHOP4FREE',
  yourProgress: 'Your progress',
  currentBalance: 'Current balance',
  earnMoreCredits: 'Earn More Credits',
  shop4freeNow: 'SHOP4FREE Now!',
  confirm: 'Confirm',
  purchases: 'Purchases',
  confirmPurchases: 'Do you want to use {{number}} credit to get this product?',
  myCart: 'My cart',
  congratulations: 'Congratulations',
  youGetCredit: 'You get {{numberCredit}} credit by ordering {{numberProduct}} products together',
  checkout: 'Checkout',
  location: 'Location',
  savings: 'Savings',
  youSaveAverageForAllProducts: 'You save average {{numberSave}}% for all products',
  all: 'All',
  subtotal: 'Subtotal',
  totalDiscount: 'Total discount',
  discount: 'Discount',
  total: 'Total',
  placeOrder: 'Place order',
  totalSavedAverage: 'Total saved average',
  quantity: 'Quantity',
  postalCode: 'Postal code',
  city: 'City',
  country: 'Country',
  state: 'State',
  street: 'Street',
  makeAsDefault: 'Make this as default',
  billing: 'Billing',
  address: 'Address',
  addNewAddress: 'Add new address',
  addAddress: 'Add Address',
  bankPayment: 'Bank payment',
  totalAmount: 'Total amount',
  makePaymentToAccount: 'Please make payment to the following account.',
  bankTransfer: 'Bank transfer',
  copyAccountNumber: 'Copy your Mari Savings Account number below',
  initiateFastTransfer: 'Initiate a FAST transfer from another bank account.',
  uploadTransactionSlip: 'Upload your Transaction Slip',
  chooseFile: 'Choose File',
  uploadDocumentNote: 'Upload your document when you have completed the payment and click make payment in the right side to complete the order',
  makePayment: 'Make payment',
  paymentReference: 'Payment reference',
  amountToPay: 'The amount to pay',
  uploadDocument: 'Upload document',
  freeShipping: 'Free shipping',
  businessDays: '{{number}} business days',
  youWillGet: 'You will get',
  numberCredit: '{{number}} credits',
  ifYouOrder: 'if you order',
  numberProductTogether: '{{number}} product together',
  itsAslo: `It's also`,
  environmentFriendly: 'environment friendly',
  creditCard: 'Credit card',
  cashOnDelivery: 'Cash on delivery',
  paymentMethod: 'Payment method',
  selectPaymentMethod: 'Select payment method',
  buyNow: 'Buy now',
  addToCart: 'Add to cart',
  saveThePlanetInitiative: 'Save the planet initiative',
  deleteSuccess: 'Deleted successfully',
  shippingFee: 'Shipping fee',
  inclVAT: 'Incl. VAT',
  excVAT: 'Excl. VAT',
  notProductOnCard: 'No products in the cart. Please add products before proceeding',
  buyProduct: 'Buy product',
  shipping: 'Shipping',
  salutation: 'Salutation',
  addProductToCartSuccess: 'Product added to cart successfully',
  addressList: 'Address list',
  copyToBillingAddress: 'Copy to Billing Address',
  copyToShippingAddress: 'Copy to Shipping Address',
  setAsShippingAddress: 'Set as Shipping Address',
  setAsBillingAddress: 'Set as Billing Address',
  defaultShippingAddress: 'Shipping address',
  defaultBillingAddress: 'Billing address',
  editAddress: 'Edit address',
  myOrder: 'My orders',
  uHaveProduct: 'You have {{number}} product in your cart',
  recent: 'Recent',
  cancelled: 'Cancelled',
  returns: 'Returns',
  shipped: 'Shipped',
  orderNumber: 'Order number',
  orderPlaceOn: 'Order placed on',
  orderItem: 'Order items',
  action: 'Action',
  manage: 'Manage',
  noProductFound: 'No product found!',
  lookLikeNoOrderList: `Looks like you haven't added anything to your Order List`,
  updateOrder: 'Update order',
  creditPrice: 'Credit price',
  shop4FreeItemsAwaitingDelivery: 'Shop4Free items awaiting delivery',
  saveForMore: 'SAVE4MORE Savings',
  buy2get1free: 'Buy 2 Get 1 Free',
  andEnjoy: 'and enjoy an',
  incredibleDiscount: 'incredible 85% discount + FREE shipping.',
  chooseYourProduct: 'Choose your products',
  chooseYourProductSubTxt: 'Explore SAVE4MORE products and add your favourites to cart.',
  selectSave4More: 'Select SAVE4MORE',
  selectSave4MoreSubTxt: 'Select the quantity and choose SAVE4MORE before checkout.',
  manageYourSubscription: 'Manage your subscriptions',
  manageYourSubscriptionTxt: 'Add or remove products, or cancel at any time.',
  joinSave4More: 'Join',
  shop4FreeMilestone: 'Next SHOP4FREE Milestone',
  learnMore: 'Learn more',
  creditBalance: 'Credit balance',
  registered: 'Registered',
  partnerDashboard: 'Partner dashboard',
  recentOrders: 'Recent orders',
  emptyOrders: 'No recent orders',
  buyWithSave4More: 'Buy With SAVE4MORE',
  joinMySubscription: 'Join my subscription',
  save4More: 'SAVE4MORE',
  reactive: 'Reactive',
  active: 'Active',
  status: 'Status',
  productNumber: 'Product number',
  orderPlacedOn: 'Order placed on',
  paymentStatus: 'Payment status',
  order: 'Order',
  orderDetails: 'Order Details',
  deliveryStatus: 'Delivery Status',
  shippedOn: 'Shipped on',
  shippingAddress: 'Shipping Address',
  trackingCode: 'Tracking Code',
  buyAgain: 'Buy Again',
  shareOrder: 'Share',
  shareToEarnMoreCredits: 'Share to earn more credits',
  shareToEarnDescription: 'You will get 15 credit if you share SAVE4MORE with your friends and loved ones.',
  shareNow: 'Share Now',
  monthBilling: '12-Month Billing',
  saveAverageDescription: 'You Save average 70% on SAVE4MORE',
  vat: 'VAT',
  creditForJoining: 'You get 15 credit for joining SAVE4MORE',
  reorder: 'Reorder',
  instalment: '1st Instalment',
  mySubscription: 'My subscription',
  subscriptionDetails: 'Subscription details',
  deliveryOn: 'Delivery on',
  youSaved: 'You Saved',
  from: 'From',
  shareVideo: 'Share Video',
  share3Video: 'Share 3 videos to earn',
  watchVideo: 'Watch Video',
  watch20Video: 'Watch 20 Videos to earn',
  luckyWheel1: '1 Lucky Wheel daily',
  luckyWheelEarn: 'Earn Lucky Wheels',
  yourInvitationCode: 'Your Invitation Code',
  myReferral: 'My Refferral',
  shareVia: 'Share Via',
  referralName: 'Name',
  referralDate: 'Refferred Date',
  inviteDate: 'Invite Date',
  referralSub: 'Start referring your friends by sharing the link below to earn lucky wheel spins',
  win: 'Win',
  productsBenefits: 'Products benefits',
  // ChatBot
  chatBotInputPlaceholder: 'Type a message...',
  chatBotTitle: 'Chat Bot',
  speechRecognition: 'Speech Recognition',
  chooseVoice: 'Choose Voice',
  offAutoSpeak: 'Off auto speak',
  settingVoiceInput: 'Setting voice input',
  // for demo
  answer0: `Hello! I'm your virtual assistant. How can I help you?`,
  answer1: 'I can help you search for information or answer your questions.',
  answer2: 'Would you like to know more about our products?',
  answer3: 'I can help you find the best deals available.',
  answer4: 'Let me know if you need any further assistance!',
  viewDetails: 'View details',
  skipIntro: 'Skip Intro',
  stayYoungerTitle: 'Stay Younger',
  stayYoungerDesc: 'Protect your cells, slow aging, and keep your body strong from within.',
  stayFitterTitle: 'Stay Fitter',
  stayFitterDesc: 'Fuel clean energy, burn fat with ketosis, and recover faster to perform at your peak.',
  stayBeautifulTitle: 'Stay Beautiful',
  stayBeautifulDesc: 'Glow inside and out — radiant skin, firm body, and confidence that lasts.',
  expertCoachingTitle: 'Expert Coaching',
  expertCoachingDesc: 'AI-powered coaching + science-backed\n solutions = real results you can see, feel, and sustain.',
  // TopRisk component translations
  top3RiskFactorsTitle: 'Top 3 Risk Factors',
  top3IllnessRisksTitle: 'Top 3 Illness Risks',
  preventiveHealthGoalTitle: 'Preventive Health Goal',
  topRiskSummaryText: 'Here are your Top 3 Risk Factors, Illness Risks and Preventive Health Goal.',
  // WeightHeight component translations
  weightLabel: 'Weight',
  heightLabel: 'Height',
  bodyMassIndexLabel: 'Body Mass Index',
  // RiskFactor component translations
  learnMoreVideoText: `Learn more about our key ingredients and benefits for {{nameLevel}}.`,
  peakPerformerTitle: 'Fantastic, you are a true ',
  peakPerforTitle: 'Awesome, you truly are a',
  peakPerforDescreption: 'Peak performer',
  discoverTop3: 'Discover our top 3 ingredients and benefits for Peak Performer.',
  healthQuestionnaire: 'Start with a short health questionnaire to unlock your personalised path to losing weight.',
  ingredientsAndBenefits: 'Ingredients and Benefits',
  trainingPlan: 'Training Plan',
  productDeal: 'Product Deal',
  testimonialSpeech: 'Discover real Peak Performer Bundle Stories That Truly Work.',
  trainingPlanSpeech: 'Start your day with our Daily Training Guide designed for a Peak Performer like you. Renew Life Capsules, Keto Slim Shake & Omega Fusion Patch',
  productDealSpeech: 'Get your Peak Performer Bundle deal now!. Bundle includes Renew Life Capsules, Keto Slim Shake & Omega Fusion Patch',
  hiAISolomonSpeech: 'Hi there, \nI’m Solomon!',
  hiIntroductionAISolomonSpeech: 'I’m a next generation AI assistant here to help you achieve your goals faster. \n\nLet’s explore your needs so I can make success feel effortless.',
  hiAddressAISolomonSpeech: 'How do I address you?',
  hiInputNameSpeech: 'Please tell me your name…',
  hiInputNicknameSpeech: 'What should I call you instead?',
  hiWelcomeWithNameSpeech: (nickname: string) => `Lovely to meet you, ${nickname}. Let’s get started to achieve your goals. How can I help you today?`,
  additionGoalSpeech: 'Tell us your additional goals, pick 3 from the top favourites!',
  imSpeedSpeech: 'How would you like your Improvement Speed ?',
  hiInputNameLabel: 'Nice to meet you, I’m...',
  hiInputNicknameLabel: 'But you can call me...',
  shippingMethod: 'Shipping method',
  later: 'Later',
  hereSomeSuggestions: `Here're some suggestions:`,
  dealEndsIn: 'AI Solomon Deal ends in',
  introduction: 'Introduction',
  trainingPlanTitle: (rf: string) => `Start your day with our Daily Training Guide designed for a ${rf} like you.`,
  productDealTitleH: `Get your`,
  productDealTitleF: `deal now!`,
  finalNote: 'Final Note',
  join4Free: 'Join For Free',
  joinSave4MoreClub: 'Join SAVE4MORE CLUB Now!',
  oneTimePurchase: 'One-time Purchase',
  buy2Get3: 'Buy 2 and Get 3 Now!',
  saveWithSave4More: (percent: string) => `Save ${percent}% with SAVE4MORE`,
  productTestimonialTitleH: 'Discover real',
  productTestimonialTitleF: 'That Truly Work.',
  peakPerformerBundle: 'Peak Performer Bundle Stories',
  noData: 'No data',
  pdfSent: 'The PDF will be sent to you via email.',
  downloadPdf: 'Download PDF',
  orderSummary: 'Order Summary',
  firstSave4MoreOrder: 'on the first SAVE4MORE order',
  join4More: 'Join SAVE4MORE',
  goToShoppingProduct: 'Go to shopping product',
  billingCityError: 'Please enter city to checkout',
  shippingStreetError: 'Please enter address to checkout',
  billingZipcodeError: 'Please enter postal code to checkout',
  shippingPhoneError: 'Please enter phone number to checkout',
  buyProductLater: 'Buy product later',
  shareTheGoodNews: 'Share the Good News',
  giveWhatsappNumbers: 'Give 5 valid WhatsApp numbers and get another ✨',
  getCreditsNow: '500 credits (€50) right now!',
  whatsappNumber: 'WhatsApp Number',
  skipInviteFriendsTitle: 'Skip Invite Friends',
  skipInviteFriendsDesc: 'You did not submit 5 phone numbers. You will miss out on earning credits. Tap "Cancel" to fill up 5 numbers.',
  congratulationsDesc: 'You have submitted 5 phone numbers. You can expect to receive credits in the next 48 hours.',
  sendInviteError: 'Send invite got error, please try again',
  study: 'Study',
  effect: 'Effect',
  searchCountryCode: 'Search country/code...',
  searchPlaceHolderText: 'Search for content...',
  backToPurchase: 'Back to Purchase',
  aiSolomon: 'AI Solomon',
  aiBeautyWellnessCoach: 'AI Beauty & Wellness Coach',
  purchaseLater: 'Purchase later',
  account: 'Account',
  healthQuestionnaireTitle: 'Health questionnaire',
  activity: 'Activity',
  activeDeals: 'Active deals',
  myStory: 'My story',
  settingsAndPrivacy: 'Settings & privacy',
  changePassword: 'Change password',
}
export default en;
