import { iLocalization } from '../iLocalization';

const vi: iLocalization = {
  en: 'Tiếng Anh',
  vi: 'Tiếng Việt',
  ja: 'Tiếng Nhật',
  ko: 'Tiếng Hàn',
  de: 'Tiếng Đức',
  th: 'Tiếng Thái',
  sk: 'Tiếng Slovak',
  hi: 'Tiếng Ân Độ',
  zh: 'Tiếng Trung',
  login: 'Đăng nhập',
  logout: 'Đăng xuất',
  signup: 'Đăng ký',
  home: 'Trang chủ',
  cart: 'Thêm video',
  addStream: 'Thông báo',
  notification: 'Giỏ hàng',
  aiStream: 'Stream',
  categories: 'Ngành hàng',
  profile: 'Tài khoản',
  loading: 'Đang tải...',
  changeLanguage: 'Đổi ngôn ngữ',
  tokenTimeout: 'Hết hạn phiên đăng nhập',
  welcomeBack: 'Chào mừng trở lại',
  welcomeBackSubTxt: 'Ưu đãi tuyệt vời đang chờ!',
  or: 'Hoặc',
  dontHaveAccount: 'Chưa có tài khoản?',
  forgotPassword: 'Quên mật khẩu',
  rememberMe: 'Ghi nhớ tôi',
  myUpload: 'Video của tôi',
  createVideo: 'Tạo mới video',
  delete: 'Xoá',
  edit: 'Sửa',
  deleteAiStream: 'Xoá video',
  subDeleteAiStream: 'Bạn có chắc rằng muốn xoá video?',
  keepIt: 'Giữ',
  deleteIt: 'Xoá',
  saveClip: 'Các clip đã lưu',
  createStream: 'Tạo mới stream',
  reportUs: 'Báo cáo với chúng tôi',
  report: 'Báo cáo',
  block: 'Chặn',
  whatIsIssue: 'Vấn đề là gì?',
  inappropriateContent: 'Nội dung không phù hợp',
  spamMisleading: 'Spam hoặc gây hiểu nhầm',
  copyrightInfringement: 'Vi phạm bản quyền',
  harassmentBullying: 'Quấy rối hoặc bắt nạt',
  other: 'Khác',
  sendReport: 'Gửi báo cáo',
  goToLogin: 'Về màn đăng nhập',
  goToLoginSubTxt: 'Nhiều ưu đãi tuyệt vời đang chờ!',
  yes: 'Có',
  no: 'Không',
  signUpTxt: 'Tạo mới tài khoản',
  subSignUpTxt: 'Chúng tôi có 3 bước để tạo tài khoản',
  chooseDetail: 'Thực hiện bài đánh giá sức khỏe',
  chooseDetailSub: 'Hành trình sức khỏe của bạn bắt đầu từ sự rõ ràng!',
  shareDeal: 'Khám phá các yếu tố rủi ro của bạn',
  shareDealSub: 'Phát hiện sớm rủi ro để luôn khỏe mạnh và hạnh phúc!',
  optionFree: 'Khám phá kế hoạch hành động dành cho bạn',
  optionFreeSub: 'Mở khóa hướng dẫn chăm sóc sức khỏe cá nhân hóa!',
  alreadyHaveAnAccount: 'Bạn đã có tài khoản',
  basicInterest: 'Sở thích',
  chooseLanguage: 'Chọn ngôn ngữ',
  back: 'Quay lại',
  next: 'Tiếp theo',
  createAccount: 'Tạo tài khoản',
  firstName: 'Họ',
  lastName: 'Tên',
  birthday: 'Ngày sinh',
  phone: 'Số điện thoại',
  email: 'Email',
  password: 'Mật khẩu',
  yourInterest: 'Sở thích của bạn',
  iAgree: 'Tôi đồng ý với',
  termsAndPrivacy: 'điều khoản và',
  conditions: 'điều kiện.',
  addEmail: 'Thêm email để mời và kiếm thưởng',
  addLucky: '✨ 1 lượt quay may mắn',
  weekly: 'hàng tuần',
  skip: 'Bỏ qua',
  sendNow: 'Gửi ngay',
  spin: 'Quay',
  luckyWheel: 'Vòng quay may mắn',
  rewards: 'Phần thưởng',
  friendsInvited: 'Bạn bè được mời',
  days: 'Ngày',
  remainingTime: 'Thời gian còn lại',
  toExpiry: 'Hết hạn',
  selectYourProduct: 'Chọn sản phẩm của bạn',
  maximumSize: 'Kích thước tối đa: 100 MB, thời lượng video: 120 giây.',
  fileFormats: 'Định dạng tệp',
  recommendedMp4: 'Khuyến nghị: ".mp4". Các định dạng phổ biến khác đều được hỗ trợ.',
  aspectRatios: 'Tỷ lệ khung hình',
  recommendedRecom: 'Khuyến nghị: 16:9 cho nằm ngang, 9:16 cho dọc.',
  selectVideoToUpload: 'Chọn video để tải lên',
  selectVideo: 'Chọn video',
  englishEUStore: 'Cửa hàng EU - Tiếng Anh',
  germanEUStore: 'Cửa hàng EU - Tiếng Đức',
  thailandStore: 'Cửa hàng Thái Lan - Tiếng Thái',
  myProfile: 'Hồ sơ của tôi',
  inviteFriends: 'Mời bạn bè',
  inviteFriendsSubTxt: 'Mời bạn bè và nhận 100 điểm cho mỗi lời mời.',
  blockList: 'Danh sách chặn',
  ourSocials: 'Mạng xã hội của chúng tôi',
  discoverBestDealsTitle: 'Khám phá những ưu đãi tốt nhất',
  discoverBestDealsDescription: 'Mua sắm các ưu đãi hàng đầu và ưu đãi độc quyền chỉ dành cho bạn!',
  earnRewardsTitle: 'Nhận phần thưởng khi mua sắm',
  earnRewardsDescription: 'Nhận thưởng cho các giao dịch mua của bạn với điểm thưởng và phần thưởng đặc biệt. Mua càng nhiều, tiết kiệm càng lớn!',
  shopWithConfidenceTitle: 'Mua sắm một cách tự tin',
  shopWithConfidenceDescription: 'Chúng tôi ở đây để làm cho trải nghiệm mua sắm của bạn trở nên dễ dàng và không lo lắng, bởi vì sự hài lòng của bạn là ưu tiên hàng đầu của chúng tôi.',
  getTheBestAndBeHappy: 'Tận hưởng những điều tốt đẹp nhất và\n Hạnh phúc',
  best: 'Tốt nhất',
  and: 'và',
  be: 'Hãy',
  happy: 'Vui vẻ',
  getStarted: 'Bắt đầu',
  affiliateCode: 'Mã liên kết',
  personalInformation: 'Thông tin cá nhân',
  fullName: 'Họ và tên',
  displayName: 'Tên hiển thị',
  emailAddress: 'Địa chỉ email',
  myInterest: 'Sở thích của tôi',
  addInterest: 'Thêm sở thích',
  editPersonalInformation: 'Chỉnh sửa thông tin cá nhân',
  close: 'Đóng',
  add: 'Thêm',
  update: 'Cập nhật',
  unBlock: 'Bỏ chặn',
  today: 'Hôm nay',
  yesterday: 'Hôm qua',
  streamSharedSuccessfully: 'Chia sẻ Stream thành công',
  copySuccess: 'Copy thành công',
  blockUserSuccess: 'Chặn người dùng thành công',
  follow: 'Theo dõi',
  following: 'Đang theo dõi',
  loadingStreamError: 'Gặp lỗi khi nạp nội dung video. Vui lòng thử lại',
  minPassword: 'Mật khẩu cần ít nhất 8 kí tự',
  createAccountSuccess: 'Tạo tài khoản thành công',
  noThanks: 'Không cảm ơn',
  loginNow: 'Đăng nhập ngay',
  followers: 'Người theo dõi',
  errorSystem: 'Lỗi hệ thống vui lòng thử lại sau.',
  changeVideo: 'Đổi video',
  discardPost: 'Huỷ thay đổi video',
  videoTitle: 'Tiêu đề video',
  selectProduct: 'Chọn sản phẩm',
  shortDescription: 'Mô tả ngắn',
  invalidEmail: 'Email không hợp lệ',
  atLeastOneEmail: 'Bạn cần nhập ít nhất 1 email',
  selectVideoFormLib: 'Từ thư viện',
  takeVideoLive: 'Từ camera',
  requiredField: 'Đây là trường bắt buộc',
  reportedSuccessfully: 'Cảm ơn bạn đã báo cáo',
  editAiStream: 'Chỉnh sửa AI stream',
  deleteAiStreamSuccess: 'Xoá video thành công',
  deleteAiStreamFailed: 'Xoá video thất bại',
  businessName: 'Tên hiển thị',
  updateProfileSuccess: 'Cập nhật thông tin người dùng thành công',
  updateProfileFailed: 'Cập nhật thông tin người dùng thất bại',
  gotoSetting: 'Đến cài đặt',
  cancel: 'Huỷ',
  askCameraTitle: 'Cho phép AISolomon truy cập vào máy ảnh của bạn?',
  askCameraMessage: 'Cho phép truy cập vào máy ảnh của bạn để chụp ảnh và quay video',
  askLibraryTitle: 'Cho phép AISolomon truy cập vào thư viện của bạn?',
  askLibraryMessage: 'Cho phép truy cập vào thư viện của bạn để lấy ảnh và video',
  avatarUpdated: 'Cập nhật hình đại diện thành công',
  somethingWrong: 'Sự cố bất ngờ, vui lòng thử lại',
  somethingWrongWhenOpenLink: 'Sự cố bất ngờ khi mở liên kết, vui lòng thử lại',
  descriptionLuckyWheel: 'Quay để có cơ hội giành giải thưởng lớn.',
  gotIt: 'Đã hiểu',
  congratulation: 'Chúc mừng!',
  congratulationTxt: 'Bạn đã nhận được phần thưởng là',
  turnRemain: 'Số lần quay còn lại',
  connectToServerErr: 'Kết nối đến máy chủ gặp lỗi, vui lòng thử lại',
  waitToConfirm: 'Đang chờ xác nhận',
  changeLanguageSuccess: 'Thay đổi ngôn ngữ thành công',
  changeLanguageFailed: 'Hệ thống có lỗi! Vui lòng thử lại sau',
  spinTurn: 'Lượt quay',
  warning: 'Warning',
  pleaseBuyProduct: 'Cần mua hàng trước để có thẻ Sản phẩm',
  likedWillAppearHere: 'Lượt like sẽ xuất hiện ở đây',
  somethingWentWrong: 'Đã có lỗi xảy ra',
  errConent: 'Đã có lỗi kết nối mang. Vui lòng thử lại sau vài phút',
  descriptionLetter: 'Có, tôi muốn đăng ký nhận bản tin AISolomon miễn phí. (Bạn có thể hủy đăng ký bất kỳ lúc nào.)',
  copyLink: 'Chép link',
  shareWithFriend: 'Chia sẻ với bạn bè',
  shareWithFriendSubText: 'Giới thiệu bạn bè mua hàng và kiếm điểm tín dụng để nhận sản phẩm MIỄN PHÍ',
  topProduct: 'Top sản phẩm',
  saving: 'Giảm giá',
  notiWillAppearHere: 'Thông báo sẽ hiện thị ở dây',
  videoGuide: 'Hướng dẫn tạo video',
  iUnderstood: 'Tôi đã hiểu',
  search: 'Tìm kiếm',
  titleModalReportAndBlock: 'Báo cáo và chặn',
  descriptionModalReportAndBlock: 'Gửi lý do và chặn người dùng',
  unsaveSuccess: 'Bỏ lưu trữ thành công',
  makeChanges: 'Thay đổi',
  makeChangesSubText: 'Bạn có thể chỉnh sửa bài đăng của mình hoặc xóa bài đăng',
  view: 'Xem',
  dontShowAgain: 'Không hiển thị lại nữa',
  love: 'Yêu thích',
  addAnother: 'Thêm một email khác',
  invalidPhone: 'Số điện thoại không hợp lệ',
  threeStepCreateAccount: 'Có 3 bước để tạo tài khoản sau đây',
  confirmPassword: 'Nhập lại mật khẩu',
  basicInformation: 'Thông tin cơ bản',
  chooseGallery: 'Chọn từ thư viện',
  updateVideo: 'Cập nhật video',
  preview: 'Xem trước',
  addProduct: 'Thêm sản phẩm',
  addACatchyTitle: 'Thêm tiêu đề',
  addAShortDes: 'Thêm mô tả ngắn',
  rePassword: 'Mật khẩu không khớp. Vui lòng nhập lại.',
  daysRemaining: 'Ngày còn lại',
  deleteOrDeactivate: 'Xoá hoặc vô hiệu hoá',
  deactivateAccount: 'Vô hiệu hóa tài khoản',
  deleteAccount: 'Xoá tài khoản',
  deleteOrDeactivateAccount: 'Xoá hoặc Vô hiệu hóa tài khoản',
  deleteAccountPermanently: 'Xóa tài khoản vĩnh viễn',
  titleDeleteOrDeactivate: 'Nếu bạn muốn tạm thời rời khỏi AISolomon, bạn chỉ cần hủy kích hoạt tài khoản của mình. Thay vào đó, nếu chọn xóa tài khoản của mình, bạn sẽ không thể khôi phục tài khoản đó sau 30 ngày.',
  contentDeleteOrDeactivate: 'Không ai có thể xem tài khoản của bạn, kể cả tất cả nội dung được lưu trữ trong đó. Kích hoạt lại tài khoản của bạn và khôi phục tất cả nội dung bất cứ lúc nào.',
  contentTwoDeleteOrDeactivate: 'Tài khoản và nội dung của bạn sẽ bị xóa vĩnh viễn. Bạn có thể hủy yêu cầu xóa bằng cách kích hoạt lại tài khoản của mình trong vòng 30 ngày.',
  ifYouDeactivateYourAccount: 'Nếu bạn vô hiệu hóa tài khoản của mình',
  ifYouDeleteYourAccount: 'Nếu bạn xoá tài khoản của mình',
  noOneSeesAccount: 'Không ai có thể thấy tài khoản và nội dung của bạn.',
  infoNotStoredVisible: 'Thông tin không được lưu trong tài khoản của bạn, chẳng hạn như tin nhắn trực tiếp, có thể vẫn hiển thị với người khác.',
  shopWithMeKeepsData: 'AISolomon sẽ tiếp tục lưu dữ liệu của bạn để bạn có thể khôi phục khi kích hoạt lại tài khoản.',
  reactivateAnytime: 'Bạn có thể kích hoạt lại tài khoản và khôi phục toàn bộ nội dung bất cứ lúc nào bằng cách sử dụng thông tin đăng nhập cũ.',
  shopWithMeNoAccess: 'Bạn sẽ không thể đăng nhập và sử dụng bất kỳ dịch vụ TikTok nào với tài khoản đó.',
  loseVideos: 'Bạn sẽ mất quyền truy cập vào tất cả video của mình.',
  draftsRemoved: 'Thông tin không được lưu trên máy chủ TikTok, chẳng hạn như bản nháp, sẽ bị xóa và bạn sẽ không thể tải xuống.',
  noRefunds: 'Bạn sẽ không thể được hoàn tiền cho bất kỳ mặt hàng nào bạn đã mua hoặc nhận.',
  deactivate: 'Vô hiệu hoá',
  noThank: 'Không cảm ơn',
  deactivateNow: 'Vô hiệu hoá ngay',
  activeAnyTime: 'Bạn có thể kích hoạt lại tài khoản bất cứ lúc nào',
  affterADay: 'Sau 30 ngày, tài khoản của bạn sẽ bị xoá ngay lập tức',
  deleteNow: 'Xoá ngay',
  continue: 'Tiếp tục',
  accountDeactivatedSuccess: 'Tài khoản của bạn đã bị vô hiệu hóa thành công',
  accountDeactivatedMessage: 'Tài khoản của bạn đã bị vô hiệu hóa hoàn toàn rồi. Nếu bạn muốn sử dụng ứng dụng, vui lòng kích hoạt tài khoản của bạn.',
  goToShop: 'Đi mua sắm',
  activeMyAccount: 'Kích hoạt tài khoản của tôi',
  welcomeBackText1: 'Tài khoản của bạn đã bị vô hiệu hóa và sẽ bị xóa trong',
  welcomeBackTextTime: '20 ngày',
  welcomeBackText2: '. Nếu bạn muốn sử dụng ứng dụng, vui lòng kích hoạt tài khoản của bạn',
  registerAccountSuccess: 'Đăng ký thành công',
  createInterestSuccees: 'Tạo thành công sở thích',
  uploadVideos: 'Tải video lên và kiếm được tới 3 lượt quay mỗi ngày (tối đa 200 credits).',
  viewVideos: 'Xem 20 video, chia sẻ 3 video và nhận 1 Vòng quay may mắn mỗi ngày.',
  sendInvites: 'Gửi 10 lời mời và giành được 2 Vòng quay may mắn mỗi tuần.',
  earnLuckyWheel: 'Kiếm được 1 lượt Vòng quay may mắn cho mỗi người bạn đăng ký bằng liên kết giới thiệu của bạn.',
  watchButton: 'Xem',
  iAgreed: 'Tôi đồng ý',
  endUserLicenseAgreement: 'thỏa thuận cấp phép cho người dùng cuối',
  upload: 'Tải lên',
  share: 'Chia sẻ',
  invite: 'Mời',
  dontShareDob: 'Tôi không muốn chia sẻ ngày sinh của mình',
  enough18: 'Tôi ít nhất 18 tuổi',
  outOfTurns: 'Bạn đã hết lượt quay',
  noResultsFound: 'Không tìm thấy kết quả nào',
  noVideoFound: 'Không tìm thấy video nào!',
  posts: 'Đăng',
  actions: 'Hành động',
  removedVideo: 'Xóa video',
  descriptionRemovedVideo: 'Bạn có chắc chắn muốn xóa video này không?',
  permanentlyDeleteVideo: 'Xóa video vĩnh viễn',
  manageUser: 'Quản lý người dùng',
  welcome: 'Chào mừng',
  descriptionWelcom: 'Đăng nhập ngay để đăng video, quay Vòng quay may mắn và giành giải thưởng hấp dẫn!',
  previousResults: 'Kết quả trước đó',
  youGot: 'Bạn đã nhận được',
  updateInviteCodeSuccess: 'Cập nhật mã mời thành công',
  product: 'Sản phẩm',
  products: 'Sản phẩm',
  moreInfo: 'Thông tin thêm',
  productDetails: 'Chi tiết sản phẩm',
  shopNow: 'Mua ngay',
  save: 'Lưu',
  uHaveNotification: 'Bạn có {{number}} thông báo mới!',
  uHaveNoNotification: 'Bạn có không thông báo mới.',
  promotion: 'Khuyến mãi',
  description: 'Mô tả',
  benefits: 'Lợi ích',
  ingredients: 'Thành phần',
  showNotProduct: 'Không có sản phẩm nào có sẵn trong khu vực của bạn. Vui lòng cập nhật địa chỉ giao hàng của bạn để xem những gì còn hàng gần bạn.',
  whatIsInviteCodeModalTitle: 'Yêu cầu mã giới thiệu',
  whatIsInviteCode: 'Làm thế nào để nhận Mã giới thiệu?',
  whatIsInviteCodeSubTxt: 'Nếu ai đó giới thiệu bạn đến AISolomon, vui lòng liên hệ với người đó để xin Mã giới thiệu.',
  emptyTextAwardHistory: 'Phần thưởng danh sách sẽ xuất hiện ở đây!',
  submit: 'Gửi',
  deleteVideo: 'Xóa video',
  emptyListProduct: 'Bạn cần mua sản phẩm trên trang web để tạo video mới.',
  credits: 'Phần thưởng',
  goShop4Free: 'Đến Shop4Free',
  noSaveProductYet: 'Chưa có video đã lưu',
  deals: 'Sản phẩm',
  goShop4FreeDes: 'Kiếm điểm tín dụng để đổi sản phẩm\nmiễn phí lên đến 100%!',
  passwordRecovery: 'Khôi phục mật khẩu',
  passwordRecoverySubTxt: 'Chúng tôi sẽ gửi cho bạn một email xác nhận. Nhấp vào liên kết trong email đó để thay đổi mật khẩu của bạn.',
  sendEmail: 'Gửi email',
  passwordResetSubTxt: 'Nếu địa chỉ email được cung cấp đã được đăng ký, một email xác nhận bao gồm liên kết đặt lại mật khẩu sẽ được gửi.',
  passwordResetBtn: 'Xác nhận',
  noUserFound: 'Không tìm thấy người dùng',
  noNotification: 'Không tìm thấy thông báo mới!',
  waitForGenLinkShare: 'Vui lòng đợi tạo đường dẫn để chia sẻ',
  recoveryPasswordSuccess: 'Yêu cầu khôi phục mật khẩu thành công vui lòng kiểm tra email',
  titleUpdateVersionApp: 'Đã có bản cập nhật mới!',
  subUpdateVersionApp: 'Hãy cập nhật ứng dụng để sử dụng những tính năng mới nhất!',
  btnUpdateVersionApp: 'Tải phiên bản mới nhất',
  titleMaintenance: 'Ứng dụng đang bảo trì',
  subMaintenance: 'Chúng tôi đang bảo trì hệ thống để nâng cao trải nghiệm. Vui lòng quay lại sau!',
  timeRemaining: 'Dự kiến hoàn thành',
  iAgreeToTermsPrivacyAndEula: 'Điều khoản, Quyền riêng tư và EULA',
  cantRemoveAllInterest: 'Bạn không thể xóa hết tất cả sở thích',
  noSpinsLeft: 'Không còn lượt quay nào',
  earnMoreLuckyWheels: 'Kiếm thêm lượt chơi Vòng Quay May Mắn',
  gotoEarn: 'Đi kiếm lượt quay',
  hide: 'Ẩn',
  more: 'Xem thêm',
  connectVideoServerErr: 'Kết nối đến Video Server gặp lỗi',
  seeRecommendForYou: 'Xem các đề xuất dành cho bạn',
  aiStory: 'AI story',
  addImage: 'Thêm ảnh',
  addVideo: 'Thêm video',
  before: 'Trước',
  after: 'Sau',
  describeYourImage: 'Mô tả ảnh của bạn',
  describeYourVideo: 'Mô tả video của bạn',
  generateStoryModeVideo: 'Tạo video chế độ câu chuyện',
  aiVideo: 'Ai video',
  publishVideo: 'Đăng tải video',
  reGenerateVideo: 'Tạo lại video',
  selectImage: 'Chọn ảnh',
  describeYourProduct: 'Mô tả sản phẩm của bạn',
  deleteDraf: 'Xoá nháp',
  generatingYourStory: 'Đang khởi tạo video của bạn',
  pleaseKeepAppOpen: 'Hãy giữ ứng dụng mở',
  intro: 'Giới thiệu',
  selectVideoOrImage: 'Thêm video/ảnh',
  require: 'Bắt buộc',
  postVideo: 'Tạo video',
  storyMode: 'Chế độ story',
  createStorySuccess: 'Chúng tôi đang xử lý story AI của bạn.\nBạn sẽ được thông báo khi nó đã sẵn sàng',
  fileSizeCantOver: 'File không thể quá {{maxSize}}MB',
  writeIntroductionText: 'Viết đoạn giới thiệu',
  writeBeforeText: 'Viết nội dung trước',
  writeAfterText: 'Viết nội dung sau',
  writeProductText: 'Viết mô tả sản phẩm',
  notYourNotification: 'Điều hướng thông báo không dành cho tài khoản hiện tại',
  takePhotoOrVideo: 'Chụp Ảnh hoặc Video',
  askMicroTitle: 'Cho phép AISolomon truy cập vào microphone của bạn?',
  askMicroMessage: 'Cho phép truy cập vào microphone của bạn để ghi lại âm thanh?',
  retake: 'Tạo lại',
  useThis: 'Sử dụng',
  fileNotSupport: 'Tệp không được hỗ trợ',
  searchPlaceHolder: 'Tìm kiếm video, hình ảnh...',
  notFoundVideo: 'Lỗi! Không tìm thấy video',
  updateInterestSuccess: 'Cập nhật sở thích thành công',
  videoRanking: 'Xếp hạng video',
  yourVideoOverview: 'Tổng quan video của bạn',
  yourPerformance: 'Hiêu suất của bạn',
  totalLikes: 'Tổng số lượt thích',
  allTimeVideoStars: 'Các ngôi sao video từ trước đến giờ',
  lastWeekVideoStars: 'Các ngôi sao video tuần trước',
  todayVideoStars: 'Các ngôi sao video hôm nay',
  allTimeTopVideo: 'Đứng đầu video từ trước đến giờ',
  lastWeekTopVideo: 'Đứng đầu video tuần trước',
  todaysTopVideo: `Đứng đầu video hôm nay`,
  videoStarsRanking: 'Xếp hạng video sao',
  noRankingYet: 'Chưa có xếp hạng nào!',
  uploadClaimTheTopSpot: ' Tải lên video của bạn ngay bây giờ và là người đầu tiên giành vị trí hàng đầu!',
  rank: 'Xếp hạng',
  user: 'Người dùng',
  likes: 'Lượt thích',
  watch: 'Xem',
  videos: 'Videos',
  avgLikePerVideo: 'Trung bình {{number}} lượt thích một video',
  youNeedUpload: 'Bạn cần tải lên {{number}} video để đạt hạng nhất.',
  uploadVideosToWin: 'Tải video lên để chiến thắng!!!',
  shareTopVideo: 'Share top video',
  postNewVideo: 'Post new video',
  toViewYourPerformance: 'để xem hiệu suất của bạn',
  rankingPeriod: 'Thời gian xếp hạng: từ {{startTime}} đến {{endTime}}',
  totalVideos: 'Tổng số videos',
  avgLikes: 'Trung bình lượt thích',
  topUserRank: 'Xếp hạng người dùng hàng đầu',
  topCreatorsRealImpact: 'Nhà sáng tạo hàng đầu, tác động thực sự. Xem ai đang dẫn đầu!',
  winAmazingPrizes: 'Giành những phần thưởng tuyệt vời!',
  videoStarHeading: 'Bạn có phải là NGÔI SAO VIDEO của AISolomon?',
  videoStarSubheading: 'Giành iPhone, laptop, chuyến du lịch và hơn 1 triệu credits với các phần quà giá trị!',
  prize1stPlace: '1 Chuyến du lịch sang trọng trọn gói đến Maldives cho 2 người!!!',
  prize2ndPlace: '1 Chiếc laptop Apple MacBook Air cao cấp',
  prize3rdTo5thPlace: 'Mỗi người 1 chiếc iPhone 16',
  creditsEach: 'Credits mỗi người',
  youAreLeading: 'Bạn đang dẫn đầu! Đừng quên tải lên để giữ vị trí đầu!',
  newUserProgram: 'Chương trình người dùng mới',
  videoStarRanking: 'Xếp hạng sao video',
  noVideoAvailable: 'Không có video nào',
  setting: 'Cài đặt',
  biometricAuthPrompt: 'Xác thực để đăng nhập bằng sinh trắc học',
  usePassword: 'Dùng mật khẩu',
  openBiometricId: 'Dùng sinh trắc học để đăng nhập',
  // Biometric error messages
  error: 'Lỗi',
  noSavedCredentials: 'Không tìm thấy thông tin đăng nhập đã lưu cho xác thực sinh trắc học',
  failedDecryptCredentials: 'Không thể giải mã thông tin đăng nhập đã lưu',
  biometricTempUnavailable: 'Sinh trắc học tạm thời không khả dụng',
  tooManyFailedAttempts: 'Quá nhiều lần thử thất bại. Vui lòng sử dụng mật khẩu để đăng nhập.',
  biometricLocked: 'Sinh trắc học bị khóa',
  biometricTempLocked: 'Xác thực sinh trắc học của bạn đã bị khóa tạm thời. Vui lòng sử dụng mật khẩu thay thế.',
  authenticationFailed: 'Xác thực thất bại',
  authenticationError: 'Đã xảy ra lỗi trong quá trình xác thực',
  biometricAuthentication: 'Xác thực sinh trắc học',
  biometricNoAccessMessage: 'Xác thực sinh trắc học không có quyền truy cập, vui lòng bật nó trong cài đặt.',
  unknownError: 'Lỗi không xác định',
  success: 'Thành công',
  biometricAuthSuccess: 'Xác thực sinh trắc học thành công',
  biometricPermissionGranted: 'Đã cấp quyền sinh trắc học',
  shop4Free: 'SHOP4FREE',
  yourProgress: 'Your progress',
  currentBalance: 'Current balance',
  earnMoreCredits: 'Earn More Credits',
  shop4freeNow: 'SHOP4FREE Ngay!',
  confirm: 'Đồng ý',
  purchases: 'Mua',
  confirmPurchases: 'Bạn có muốn sử dụng {{number}} điểm thưởng để mua sản phẩm này?',
  myCart: 'Giỏ hàng của tôi',
  congratulations: 'Chúc mừng',
  youGetCredit: 'Bạn nhận được {{numberCredit}} điểm khi đặt {{numberProduct}} sản phẩm cùng lúc',
  checkout: 'Thanh toán',
  location: 'Vị trí',
  savings: 'Tiết kiệm',
  youSaveAverageForAllProducts: 'Bạn tiết kiệm trung bình {{numberSave}}% cho tất cả các sản phẩm',
  all: 'Tất cả',
  subtotal: 'Tổng phụ',
  totalDiscount: 'Tổng giảm',
  discount: 'Giảm giá',
  total: 'Tổng',
  placeOrder: 'Đặt hàng',
  totalSavedAverage: 'Bạn đã tiết kiệm được tổng',
  quantity: 'Số lượng',
  postalCode: 'Mã bưu điện',
  city: 'Thành phố',
  country: 'Quốc gia',
  state: 'Bang/Tỉnh',
  street: 'Đường',
  makeAsDefault: 'Đặt làm mặc định',
  billing: 'Thanh toán',
  address: 'Địa chỉ',
  addNewAddress: 'Thêm mới địa chỉ',
  addAddress: 'Thêm địa chỉ',
  bankPayment: 'Thanh toán ngân hàng',
  totalAmount: 'Tổng số tiền',
  makePaymentToAccount: 'Vui lòng thanh toán vào tài khoản sau.',
  bankTransfer: 'Chuyển khoản ngân hàng',
  copyAccountNumber: 'Sao chép số tài khoản Mari của bạn bên dưới',
  initiateFastTransfer: 'Thực hiện chuyển khoản nhanh từ tài khoản ngân hàng khác.',
  uploadTransactionSlip: 'Tải lên biên lai giao dịch của bạn',
  chooseFile: 'Chọn tệp',
  uploadDocumentNote: 'Tải lên tài liệu của bạn khi bạn đã hoàn tất thanh toán và nhấp vào thanh toán ở bên phải để hoàn tất đơn hàng',
  makePayment: 'Thanh toán',
  paymentReference: 'Tham chiếu thanh toán',
  amountToPay: 'Số tiền cần thanh toán',
  uploadDocument: 'Tải tệp lên',
  freeShipping: 'Miễn phí vận chuyển',
  businessDays: '{{number}} ngày làm việc',
  youWillGet: 'Bạn sẽ nhận được',
  numberCredit: '{{number}} tín dụng',
  ifYouOrder: 'nếu bạn đặt hàng',
  numberProductTogether: '{{number}} sản phẩm cùng lúc',
  itsAslo: 'Nó cũng',
  environmentFriendly: 'thân thiện với môi trường',
  creditCard: 'Thẻ tín dụng',
  cashOnDelivery: 'Thanh toán khi nhận hàng',
  paymentMethod: 'Phương thức thanh toán',
  selectPaymentMethod: 'Chọn phương thức thanh toán',
  buyNow: 'Mua ngay',
  addToCart: 'Thêm vào giỏ hàng',
  saveThePlanetInitiative: 'Sáng kiến cứu trái đất',
  deleteSuccess: 'Xoá thành công',
  shippingFee: 'Phí giao hàng',
  inclVAT: 'Bao gồm VAT',
  excVAT: 'Chưa bao gồm VAT',
  notProductOnCard: 'Chưa có sản phẩm trong giỏ hàng. Vui lòng thêm sản phẩm vào giỏ hàng trước',
  buyProduct: 'Mua sản phẩm',
  shipping: 'Giao hàng',
  salutation: 'Danh xưng',
  addProductToCartSuccess: 'Thêm sản phẩm vào giỏ hàng thành công',
  addressList: 'Danh sách địa chỉ',
  copyToBillingAddress: 'Sao chép sang địa chỉ thanh toán',
  copyToShippingAddress: 'Sao chép sang địa chỉ giao hàng',
  setAsShippingAddress: 'Đặt làm địa chỉ giao hàng',
  setAsBillingAddress: 'Đặt làm địa chỉ thanh toán',
  defaultShippingAddress: 'Địa chỉ giao hàng mặc định',
  defaultBillingAddress: 'Địa chỉ thanh toán mặc định',
  editAddress: 'Sửa địa chỉ',
  myOrder: 'Đơn hàng của tôi',
  uHaveProduct: 'Bạn có {{number}} sản phẩm trong giỏ hàng!',
  recent: 'Đơn hàng gần đây',
  cancelled: 'Đã hủy',
  returns: 'Trả hàng',
  shipped: 'Đã giao',
  orderNumber: 'Mã đơn hàng',
  orderPlaceOn: 'Đặt hàng vào ngày',
  orderItem: 'Sản phẩm đã đặt',
  action: 'Thao tác',
  manage: 'Quản lý',
  noProductFound: 'Không tìm thấy sản phẩm!',
  lookLikeNoOrderList: 'Có vẻ như bạn chưa thêm gì vào danh sách đơn hàng',
  updateOrder: 'Chỉnh sửa đơn hàng',
  creditPrice: 'Giá quy đổi điểm',
  shop4FreeItemsAwaitingDelivery: 'Sản phẩm Shop4Free đang chờ giao',
  saveForMore: 'Tiết kiệm SAVE4MORE',
  buy2get1free: 'Mua 2 tặng 1',
  andEnjoy: 'và tận hưởng',
  incredibleDiscount: 'mã giảm giá lên tới 85% + MIỄN PHÍ vận chuyển',
  chooseYourProduct: 'Chọn sản phẩm',
  chooseYourProductSubTxt: 'Khám phá sản phẩm SAVE4MORE và bỏ vào giỏ những món hàng bạn yêu thích.',
  selectSave4More: 'Chọn SAVE4MORE',
  selectSave4MoreSubTxt: 'Lựa chọn số lương sản phẩm và chọn SAVE4MORE trước khi lên đơn.',
  manageYourSubscription: 'Quản lý các đăng ký của bạn',
  manageYourSubscriptionTxt: 'Thêm hoặc xoá sản phẩm,thậm chí huỷ mọi lúc nếu muốn.',
  joinSave4More: 'Trải nghiệm',
  shop4FreeMilestone: 'Cột mốc SHOP4FREE tiếp theo',
  learnMore: 'Tìm hiểu thêm',
  creditBalance: 'Số dư tín dụng',
  registered: 'Đã đăng ký',
  partnerDashboard: 'Bảng điều khiển đối tác',
  recentOrders: 'Đơn hàng gần đây',
  emptyOrders: 'Không có đơn hàng gần đây',
  buyWithSave4More: 'Mua với SAVE4MORE',
  joinMySubscription: 'Tham gia gói đăng ký của tôi',
  save4More: 'SAVE4MORE',
  reactive: 'Kích hoạt lại',
  active: 'Đang hoạt động',
  status: 'Trạng thái',
  productNumber: 'Mã sản phẩm',
  orderPlacedOn: 'Đặt hàng vào ngày',
  paymentStatus: 'Trạng thái thanh toán',
  order: 'Đơn hàng',
  orderDetails: 'Chi Tiết Đơn Hàng',
  deliveryStatus: 'Trạng thái giao hàng',
  shippedOn: 'Đã gửi vào',
  shippingAddress: 'Địa chỉ giao hàng',
  trackingCode: 'Mã theo dõi',
  buyAgain: 'Mua lại',
  shareOrder: 'Chia sẻ',
  shareToEarnMoreCredits: 'Chia sẻ để kiếm thêm điểm',
  shareToEarnDescription: 'Bạn sẽ nhận được 15 điểm nếu chia sẻ SAVE4MORE với bạn bè và người thân.',
  shareNow: 'Chia sẻ ngay',
  monthBilling: 'Thanh toán 12 tháng',
  saveAverageDescription: 'Bạn tiết kiệm trung bình 70% với SAVE4MORE',
  vat: 'VAT',
  creditForJoining: 'Bạn nhận được 15 điểm khi tham gia SAVE4MORE',
  reorder: 'Đặt lại',
  instalment: 'Kỳ thanh toán 1',
  mySubscription: 'Gói đăng ký của tôi',
  subscriptionDetails: 'Chi tiết gói đăng ký',
  deliveryOn: 'Giao hàng vào',
  youSaved: 'Bạn đã tiết kiệm',
  from: 'Từ',
  shareVideo: 'Chia sẻ video',
  share3Video: 'Chia sẻ 3 video để nhận thưởng',
  watchVideo: 'Xem video',
  watch20Video: 'Xem 20 video để nhận thưởng',
  luckyWheel1: '1 vòng quay may mắn mỗi ngày',
  luckyWheelEarn: 'Nhận vòng quay may mắn',
  yourInvitationCode: 'Mã mời của bạn',
  myReferral: 'Giới thiệu của tôi',
  shareVia: 'Chia sẻ qua',
  referralName: 'Tên',
  referralDate: 'Ngày được giới thiệu',
  inviteDate: 'Ngày mời',
  referralSub: 'Bắt đầu giới thiệu bạn bè bằng cách chia sẻ liên kết bên dưới để nhận lượt quay may mắn',
  win: 'Chiến thắng',
  productsBenefits: 'Lợi ích sản phẩm',
  // ChatBot
  chatBotInputPlaceholder: 'Nhập tin nhắn...',
  chatBotTitle: 'Trợ lý ảo',
  speechRecognition: 'Nhận giọng nói',
  chooseVoice: 'Chọn giọng nói',
  offAutoSpeak: 'Tắt tự động nói',
  settingVoiceInput: 'Cài đặt nhập giọng nói',
  // for demo
  answer0: 'Xin chào! Tôi là trợ lý ảo của bạn. Tôi có thể giúp gì cho bạn hôm nay?',
  answer1: 'Tôi có thể giúp bạn tìm kiếm thông tin hoặc trả lời câu hỏi của bạn.',
  answer2: 'Bạn có muốn biết thêm về các sản phẩm của chúng tôi không?',
  answer3: 'Tôi có thể giúp bạn tìm kiếm các ưu đãi tốt nhất hiện có.',
  answer4: 'Hãy cho tôi biết nếu bạn cần hỗ trợ gì thêm!',
  viewDetails: 'Xem chi tiết',
  skipIntro: 'Bỏ qua giới thiệu',
  stayYoungerTitle: 'Trẻ lâu hơn',
  stayYoungerDesc: 'Bảo vệ tế bào, làm chậm quá trình lão hóa và giữ cơ thể khỏe mạnh từ bên trong.',
  stayFitterTitle: 'Khỏe hơn',
  stayFitterDesc: 'Nạp năng lượng sạch, đốt mỡ bằng ketosis và phục hồi nhanh hơn để đạt hiệu suất tối đa.',
  stayBeautifulTitle: 'Đẹp hơn',
  stayBeautifulDesc: 'Tỏa sáng từ trong ra ngoài — làn da rạng rỡ, thân hình săn chắc và sự tự tin bền lâu.',
  expertCoachingTitle: 'Huấn luyện chuyên gia',
  expertCoachingDesc: 'Huấn luyện bằng AI + giải pháp\n dựa trên khoa học = kết quả thực sự bạn có thể thấy, cảm nhận và duy trì.',
  // TopRisk component translations
  top3RiskFactorsTitle: 'Top 3 Yếu Tố Nguy Cơ',
  top3IllnessRisksTitle: 'Top 3 Nguy Cơ Bệnh Lý',
  preventiveHealthGoalTitle: 'Mục Tiêu Sức Khỏe Phòng Ngừa',
  topRiskSummaryText: 'Đây là Top 3 Yếu tố Nguy cơ, Nguy cơ Bệnh lý và Mục tiêu Sức khỏe Phòng ngừa của bạn.',
  // WeightHeight component translations
  weightLabel: 'Cân nặng',
  heightLabel: 'Chiều cao',
  bodyMassIndexLabel: 'Chỉ số khối cơ thể',
  // RiskFactor component translations
  learnMoreVideoText: `Tìm hiểu thêm về các thành phần chính và lợi ích cho {{nameLevel}}.`,
  peakPerformerTitle: 'Tuyệt vời, bạn thực sự là một ',
  peakPerforTitle: 'Tuyệt vời, bạn thực sự là một',
  peakPerforDescreption: 'Người biểu diễn đỉnh cao',
  discoverTop3: 'Khám phá 3 thành phần và lợi ích hàng đầu dành cho Người Biểu Diễn Đỉnh Cao.',
  healthQuestionnaire: 'Bắt đầu với một bảng câu hỏi sức khỏe ngắn để mở khóa lộ trình cá nhân hóa giúp bạn giảm cân.',
  ingredientsAndBenefits: 'Thành phần và lợi ích',
  trainingPlan: 'Kế hoạch tập luyện',
  productDeal: 'Ưu đãi sản phẩm',
  testimonialSpeech: 'Khám phá những câu chuyện thực tế từ gói Peak Performer Bundle đã chứng minh hiệu quả.',
  trainingPlanSpeech: 'Bắt đầu ngày mới của bạn với Hướng Dẫn Tập Luyện Hằng Ngày, thiết kế dành riêng cho người xuất sắc như bạn. Bao gồm Renew Life Capsules, Keto Slim Shake & Omega Fusion Patch',
  productDealSpeech: 'Nhận ngay ưu đãi gói Peak Performer Bundle! Gói bao gồm Renew Life Capsules, Keto Slim Shake & Omega Fusion Patch',
  hiAISolomonSpeech: 'Xin chào, \ntôi là Solomon!',
  hiIntroductionAISolomonSpeech: 'Tôi là trợ lý AI thế hệ mới, sẵn sàng giúp bạn đạt được mục tiêu nhanh hơn. \n\nHãy cùng khám phá nhu cầu của bạn để mình giúp bạn đạt được thành công một cách dễ dàng.',
  hiAddressAISolomonSpeech: 'Tôi nên xưng hô với bạn như thế nào?',
  hiInputNameSpeech: 'Vui lòng cho tôi biết tên của bạn…',
  hiInputNicknameSpeech: 'Tôi có thể gọi bạn đơn giản là gì?',
  hiWelcomeWithNameSpeech: (nickname: string) => `Rất vui được gặp bạn, ${nickname}. Hãy cùng bắt đầu để đạt được mục tiêu của bạn. Hôm nay tôi có thể giúp gì cho bạn?`,
  additionGoalSpeech: 'Hãy cho chúng tôi biết thêm mục tiêu của bạn, chọn 3 mục tiêu yêu thích nhất!',
  imSpeedSpeech: 'Bạn muốn tốc độ cải thiện của mình như thế nào?',
  hiInputNameLabel: 'Rất vui được gặp bạn, tôi là...',
  hiInputNicknameLabel: 'Nhưng bạn có thể gọi tôi là...',
  shippingMethod: 'Phương thức vận chuyển',
  later: 'Để sau',
  hereSomeSuggestions: 'Đây là một số gợi ý:',
  dealEndsIn: 'Ưu đãi AI Solomon kết thúc sau',
  introduction: 'Giới thiệu',
  trainingPlanTitle: (rf: string) => `Bắt đầu một ngày của bạn với Hướng dẫn tập luyện hằng ngày được thiết kế dành riêng cho một ${rf} như bạn.`,
  productDealTitleH: 'Nhận ưu đãi',
  productDealTitleF: 'của bạn ngay!',
  finalNote: 'Ghi chú cuối cùng',
  join4Free: 'Tham gia miễn phí',
  joinSave4MoreClub: 'Tham gia SAVE4MORE CLUB ngay!',
  oneTimePurchase: 'Mua một lần',
  buy2Get3: 'Mua 2 tặng 3 ngay!',
  saveWithSave4More: (percent: string) => `Tiết kiệm ${percent}% với SAVE4MORE`,
  productTestimonialTitleH: `Khám phá thực sự`,
  productTestimonialTitleF: `thực sự hiệu quả.`,
  peakPerformerBundle: 'Câu chuyện Gói Người đạt thành tích đỉnh cao',
  noData: 'Không có dữ liệu',
  pdfSent: 'Tệp PDF sẽ được gửi cho bạn qua email.',
  downloadPdf: 'Tải xuống PDF',
  orderSummary: 'Tóm tắt đơn hàng',
  firstSave4MoreOrder: 'cho đơn hàng SAVE4MORE đầu tiên',
  join4More: 'Tham gia SAVE4MORE',
  goToShoppingProduct: 'Đến mua sắm sản phẩm',
  billingCityError: 'Vui lòng nhập thành phố để thanh toán',
  shippingStreetError: 'Vui lòng nhập địa chỉ để thanh toán',
  billingZipcodeError: 'Vui lòng nhập mã bưu điện để thanh toán',
  shippingPhoneError: 'Vui lòng nhập số điện thoại để thanh toán',
  buyProductLater: 'Mua sản phẩm sau',
  shareTheGoodNews: 'Chia sẻ tin tốt lành',
  giveWhatsappNumbers: 'Cung cấp 5 số WhatsApp hợp lệ và nhận thêm một cái ✨',
  getCreditsNow: 'Nhận ngay 500 credits (€50)!',
  whatsappNumber: 'Số WhatsApp',
  skipInviteFriendsTitle: 'Bỏ qua mời bạn bè',
  skipInviteFriendsDesc: 'Bạn chưa nhập đủ 5 số điện thoại. Bạn sẽ bỏ lỡ cơ hội nhận credits. Nhấn "Hủy" để nhập đủ 5 số.',
  congratulationsDesc: 'Bạn đã nhập đủ 5 số điện thoại. Bạn có thể nhận credits trong vòng 48 giờ tới.',
  sendInviteError: 'Gửi lời mời thất bại. Vui lòng thử lại sau.',
  study: 'Học hỏi',
  effect: 'Ảnh hưởng',
  searchCountryCode: 'Tìm kiếm quốc gia/mã...',
  searchPlaceHolderText: 'Tìm kiếm nội dung...',
  backToPurchase: 'Quay lại mua hàng',
  aiSolomon: 'AI Solomon',
  aiBeautyWellnessCoach: 'Huấn luyện viên AI về Sắc đẹp và Sức khỏe',
  purchaseLater: 'Mua sau',
  account: 'Tài khoản',
  healthQuestionnaireTitle: 'Bảng câu hỏi sức khỏe',
  activity: 'Hoạt động',
  activeDeals: 'Ưu đãi đang hoạt động',
  myStory: 'Câu chuyện của tôi',
  settingsAndPrivacy: 'Cài đặt & quyền riêng tư',
  changePassword: 'Đổi mật khẩu',
}
export default vi;
