import { InterestQuestion } from 'types/user';

export const interestQuestions: InterestQuestion[] = [
  {
    id: 'games',
    title: 'Ban choi game gi?',
    options: [
      'Lien Quan',
      'Valorant',
      'League of Legends',
      'PUBG',
      'Genshin Impact',
      'Minecraft',
      'FIFA / FC',
      'Khong choi game',
    ],
  },
  {
    id: 'music',
    title: 'The loai nhac yeu thich?',
    options: [
      'V-Pop',
      'K-Pop',
      'US-UK Pop',
      'Rock',
      'R&B / Soul',
      'EDM',
      'Hip-Hop / Rap',
      'Bolero',
      'Indie',
      'Classical',
    ],
  },
  {
    id: 'sports',
    title: 'Mon the thao yeu thich?',
    options: [
      'Bong da',
      'Cau long',
      'Boi loi',
      'Gym / Fitness',
      'Yoga',
      'Chay bo',
      'Bong ro',
      'Tennis',
      'Dap xe',
      'Khong choi the thao',
    ],
  },
  {
    id: 'pets',
    title: 'Thu cung dang nuoi?',
    options: [
      'Cho',
      'Meo',
      'Ca',
      'Chim',
      'Hamster',
      'Khong nuoi',
    ],
  },
  {
    id: 'food',
    title: 'So thich am thuc?',
    options: [
      'Do an Viet',
      'Do an Han',
      'Do an Nhat',
      'Do an Thai',
      'Fast food',
      'An chay / Vegan',
      'Cafe',
      'Tra sua',
    ],
  },
  {
    id: 'travel',
    title: 'Phong cach du lich?',
    options: [
      'Bien / Dao',
      'Nui / Trekking',
      'Thanh pho',
      'Camping',
      'Road trip',
      'Backpacking',
      'Nghi duong resort',
      'Chua di nhieu',
    ],
  },
];
